# Generated by Django 4.2.4 on 2023-08-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_player_name_alter_player_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pointsPerRound',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='rounds_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='timesC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='timesD',
            field=models.IntegerField(default=0),
        ),
    ]
