# Generated by Django 4.2.4 on 2023-08-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_player_points_player_pointsperround_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pointsPerRound',
            new_name='points_per_round',
        ),
    ]
