# Generated by Django 4.2.4 on 2023-08-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_player_timesc_remove_player_timesd'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(related_name='matches', to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.matchsummary')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPointPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('move', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerPointPairs', to='games.rounddata')),
            ],
        ),
    ]
